@startuml アクティビティ図の例

|Swimlane1|
|Swimlane1|
|Swimlane2|
|Swimlane2|
|Swimlane3|
|Swimlane3|

|Swimlane2|
start
  :action A;
fork
|Swimlane1|
  if () is (<color:red>条件1) then 
  #pink:action B;
|Swimlane1|
  else (<color:blue>条件2) 
|Swimlane2|
  #LightSkyBlue:action C;
|Swimlane2|
  endif

fork again
|Swimlane3|
 :action D;
  :オブジェクト]
  :action E;
|Swimlane3|
 
|Swimlane2|
end fork 
|Swimlane2|
 

|Swimlane2|
 :action F;

stop
|Swimlane2|
@enduml
