    /' デジタルカメラのシナリオ
        １）レンズカバーを開閉する。
        ２）ズームを決める。
        ３）写真を撮る。
        ４）メモリカードに保存する。
     '/
@startuml 演習3
    left to right direction
    actor ユーザー
    rectangle デジタルカメラ {
        usecase レンズカバーを開閉する
        usecase ズームを決める
        usecase 写真をとる
        usecase メモリカードに保存する
    }
    ユーザー --> レンズカバーを開閉する
    ユーザー --> ズームを決める
    ユーザー --> 写真をとる
    ユーザー --> メモリカードに保存する
@enduml