@startuml 演習4-2_SD_利用者と予約画面.pu
hide footbox
skinparam style strictuml
participant "<u>user:利用者</u>" as user
participant "<u>:予約画面</u>" as yoyaku
autonumber
activate  user
user ->> yoyaku : ログイン()
  activate  yoyaku
    yoyaku -> yoyaku : 認証()
    activate  yoyaku
    ' yoyaku --> yoyaku 
  deactivate  yoyaku
deactivate user

@enduml

