@startuml 演習6-5-1
' 演習6-5-1_クラス図_ライントレーサー

    ' class ライントレーサー{

    ' }
    ' class 光センサー{

    ' }
    ' class 左モーター{

    ' }
    ' class 右モーター{

    ' }
    ' class CPU{

    ' }
    ' class 電源SW{

    ' }
    ライントレーサー*-down-"1" 光センサー
    ライントレーサー*-down-"1"CPU
    ライントレーサー*-down-"1"電源SW
    ライントレーサー*-down-"1"左モーター
    ライントレーサー*-down-"1"右モーター
@enduml