@startuml ハンバーガーショップ

|顧客|
|顧客|
|スタッフ|
|スタッフ|
|厨房|
|厨房|

|スタッフ|
start
:挨拶をする;
:（空欄a）;
|スタッフ|

|顧客|
:注文する;
|顧客|

|スタッフ|
:（空欄b）;
fork
:（空欄c）;
|顧客|
:代金を払う;
|顧客|
|スタッフ|
:（空欄f）;
|スタッフ|

fork again
:（空欄d）;
|スタッフ|

|厨房|
:（空欄e）;
|厨房|

|スタッフ|
fork end
:（空欄g）;
if () then (テイクアウト)
:（空欄h）;
else  (店内)
:（空欄i）;
endif
:商品を渡す;
|スタッフ|

|顧客|
:商品を受け取る;
|顧客|
stop

@enduml