    /' デジタルカメラのシナリオ
盛岡商事では、新規に販売管理システムを導入します。
盛岡商事の田中さんと鈴木さんは販売部で商品の出荷を担当しています。
田中さんは注文商品をシステムで確認し、鈴木さんは商品の出荷状況をシステムに登録します。
     '/
@startuml 演習4
    left to right direction
    actor 出荷担当者
    rectangle 販売管理システム {
        usecase 注文商品を確認する
        usecase 出荷状況の登録する
    }
    出荷担当者 --> 注文商品を確認する
    出荷担当者 --> 出荷状況の登録する
@enduml