@startuml 演習8-3-1

|【空欄a】|
start
    :発注;
|【空欄a】|


|【空欄b】|
    :【空欄d】;
    :【空欄e】;
    if() then (【空欄g】)
        :; 
        note right
            作図の都合上,
            ダミーの
            アクティビティ
            を記述
        end note
        
    |【空欄c】|
    
    else (【空欄f】)
    |【空欄c】|
        :製造; 
    |【空欄c】|
    endif

    |【空欄b】|
     :発送;
    |【空欄b】|

    |【空欄a】|
     :【空欄h】;
    |【空欄a】|

|【空欄b】|
    :【空欄i】;
stop
|【空欄b】|
@enduml