@startuml ハンバーガーショップのクラス図
class a {
合計
}
hide a circle
hide a methods

class b {
数量
小計
}
hide b circle
hide b methods

class c {
値引き額
期限
}
hide c circle
hide c methods

class d {
名称
単価
}
hide d circle
hide d methods

a "1" o--right-- "1..*" b
b "0..*" --right-- "0..1" c
b "0..*" -down- "1" d

class f {
種別
}
hide f circle
hide f methods

hide g circle
hide g methods
hide g fields

d <|-l- f
d <|-- g

class e { 
サイズ
}
hide e circle
hide e methods

f "0..*"--left-- "1..3" e


hide h circle
hide h methods
hide h fields

g "1" ---right--- "1" h

class k {
    サイズ
}
hide k circle
hide k methods

class j {
    種別
}
hide j circle
hide j methods

 g <|-down- k
 g <|-down- j

hide i circle
hide i methods
' hide i fields

i "1..*"--right--o "1..*" j

i <|-d- パン
i <|-d- 肉
i <|-d- 野菜
i <|-d- チーズ

hide チーズ circle
hide チーズ methods
hide チーズ fields

hide パン circle
hide パン methods
hide パン fields

hide 肉 circle
hide 肉 methods
hide 肉 fields

hide 野菜 circle
hide 野菜 methods
hide 野菜 fields

@enduml