@startuml
hide footbox

skinparam style strictuml /' 厳密なUMLに準拠する '/
Actor "<u>:客</u>" as customer
participant "<u>:フロア店員</u>" as clerk
participant "<u>:料理人</u>" as cook


activate  customer
  customer -> clerk:ラーメンを注文する

    activate  clerk
      clerk -> cook:調理を指示する
      activate  cook
        cook -> cook : 料理する
      clerk <<-- cook:ラーメン
      deactivate cook
    
  customer <<-- clerk:ラーメン
  deactivate clerk
  
deactivate customer

@enduml

